enum ConversionActionsTypes {
  CONVERT_KM_TO_MILES = "CONVERT_KM_TO_MILES",
  CONVERT_MILES_TO_KM = "CONVERT_MILES_TO_KM",
  CONVERT_FEET_TO_METTERS = "CONVERT_FEET_TO_METTERS",
  CONVERT_METTERS_TO_FEET = "CONVERT_METTERS_TO_FEET",
  CONVERT_CM_TO_INCHES = "CONVERT_CM_TO_INCHES",
  CONVERT_INCHES_TO_CM = "CONVERT_INCHES_TO_CM",
}
